=== Metabolic24/IAWS_Project/Project/tisseoVelibService/src/main/resources/TisseoVelib.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/TisseoVelib" xmlns:tns="http://www.example.org/TisseoVelib" elementFormDefault="qualified">
	<element name="coordonnees">
		<complexType>
			<sequence>
				<element name="longitude" type="double"></element>
				<element name="latitude" type="double"></element>
			</sequence>
		</complexType>
	</element>
	
	<element name="bikestation">
		<complexType>
			<sequence>
				<element name="id" type="long"></element>
				<element name="name" type="string"></element>
				<element name="adresse" type="string"></element>
				<element name="availableBikes" type="int"></element>
				<element name="status" type="string"></element>
				<element ref="tns:coordonnees"></element>
			</sequence>
		</complexType>
	</element>
	
	<element name="transportLine">
		<complexType>
			<sequence>
				<element name="id" type="long"></element>
				<element name="name" type="string"></element>
				<element name="shortName" type="string"></element>
				<element name="nbLikes" type="int"></element>
			</sequence>
		</complexType>
	</element>
	
	<element name="user">
		<complexType>
			<sequence>
				<element name="id" type="long"></element>
				<element name="firstName" type="string"></element>
				<element name="lastName" type="string"></element>
				<element name="mail" type="string"></element>
				<element name="adress" type="string"></element>
				<element ref="tns:coordonnees"></element>
			</sequence>
		</complexType>
	</element>
	
	<!--Requests-->
	
	<element name="LikeRequest">
		<complexType>
			<sequence>
				<element name="id" type="long"></element>
				<element name="name" type="string"></element>
				<element name="shortName" type="string"></element>
				<element name="like" type="boolean"></element>								
			</sequence>
		</complexType>
	</element>
	
	<element name="NextBusMetroRequest">
		<complexType>
			<sequence>
				<element name="name" type="string"></element>
				<element name="shortName" type="string"></element>
			</sequence>
		</complexType>
	</element>
	
	<element name="AvailableBikesRequest">
		<complexType>
			<sequence>
				<element name="name" type="string"></element>
			</sequence>
		</complexType>
	</element>
	
	<!--Responses-->
	
	<element name="LikeResponse">
		<complexType>
			<sequence>
				<element name="etat" type="string"></element>
			</sequence>
		</complexType>
	</element>
	
	<element name="NextBusMetroResponse">
		<complexType>
			<sequence>
				<element name="name" type="string"></element>
				<element name="timeleft" type="int"></element>
			</sequence>
		</complexType>
	</element>
	
	<element name="AvailableBikesResponse">
		<complexType>
			<sequence>
				<element name="availableBikes" type="int"></element>
			</sequence>
		</complexType>
	</element>
</schema>

=== Metabolic24/IAWS_Project/Project/tisseoVelibService/src/main/resources/BikeStation.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:bikestation xmlns:tns="http://www.example.org/TisseoVelib" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/TisseoVelib TisseoVelib.xsd ">
  <tns:id>1</tns:id>
  <tns:name>BikeStationTest</tns:name>
  <tns:adresse>29 Rue Pablo Picasso 09600 Laroque dâ€™Olmes</tns:adresse>
  <tns:availableBikes>30</tns:availableBikes>
  <tns:status>OPEN</tns:status>
  <tns:coordonnees>
    <tns:longitude>5.8</tns:longitude>
    <tns:latitude>12.5</tns:latitude>
  </tns:coordonnees>
</tns:bikestation>

=== Metabolic24/IAWS_Project/Project/tisseoVelibService/src/main/resources/User.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:user xmlns:tns="http://www.example.org/TisseoVelib" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/TisseoVelib TisseoVelib.xsd ">
  <tns:id>0</tns:id>
  <tns:firstName>tns:firstName</tns:firstName>
  <tns:lastName>tns:lastName</tns:lastName>
  <tns:mail>tns:mail</tns:mail>
  <tns:adress>tns:adress</tns:adress>
  <tns:coordonnees>
    <tns:longitude>0.0</tns:longitude>
    <tns:latitude>0.0</tns:latitude>
  </tns:coordonnees>
</tns:user>
